create table products
(
    id                 bigint generated by default as identity primary key,
    seller_id          bigint not null,
    title              varchar(200) not null,
    description        text not null,
    price              numeric(19, 2) not null,
    image_url          varchar(2048) not null,
    available_quantity integer not null default 0,
    status             varchar(20) not null default 'DRAFT',
    created_at         timestamp with time zone not null default current_timestamp,
    updated_at         timestamp with time zone not null default current_timestamp,

    constraint chk_products_price
        check (price > 0),

    constraint chk_products_available_quantity
        check (available_quantity >= 0),

    constraint chk_products_status
        check (status in ('DRAFT', 'ACTIVE', 'ARCHIVED'))
);