services:
  user-postgres:
    image: postgres:17-alpine
    container_name: marketplace-user-postgres

    environment:
      POSTGRES_DB: marketplace_users
      POSTGRES_USER: marketplace
      POSTGRES_PASSWORD: marketplace

    ports:
      - "1011:5432"

    volumes:
      - user_postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U marketplace -d marketplace_users"
        ]
      interval: 5s
      timeout: 3s
      retries: 10

  product-postgres:
    image: postgres:17-alpine
    container_name: marketplace-product-postgres

    environment:
      POSTGRES_DB: marketplace_products
      POSTGRES_USER: marketplace
      POSTGRES_PASSWORD: marketplace

    ports:
      - "1012:5432"

    volumes:
      - product_postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U marketplace -d marketplace_products"
        ]
      interval: 5s
      timeout: 3s
      retries: 10

  user-service:
    build:
      context: .
      dockerfile: services/user-service/Dockerfile

    container_name: marketplace-user-service

    environment:
      SERVER_PORT: 8081
      DB_URL: jdbc:postgresql://user-postgres:5432/marketplace_users
      DB_USER: marketplace
      DB_PASSWORD: marketplace
      GRPC_SERVER_PORT: 9091

    ports:
      - "8081:8081"
      - "9091:9091"

    depends_on:
      user-postgres:
        condition: service_healthy

  product-service:
    build:
      context: .
      dockerfile: services/product-service/Dockerfile

    container_name: marketplace-product-service

    environment:
      SERVER_PORT: 8082
      DB_URL: jdbc:postgresql://product-postgres:5432/marketplace_products
      DB_USER: marketplace
      DB_PASSWORD: marketplace
      GRPC_SERVER_PORT: 9092
      USER_GRPC_TARGET: user-service:9091

    ports:
      - "8082:8082"
      - "9092:9092"

    depends_on:
      product-postgres:
        condition: service_healthy
      user-service:
        condition: service_started

volumes:
  user_postgres_data:
  product_postgres_data: