create table users
(
    id            bigint generated by default as identity primary key,
    username      varchar(50)  not null,
    email         varchar(255) not null,
    password_hash varchar(255) not null,
    role          varchar(20)  not null,
    created_at    timestamp with time zone not null default current_timestamp,

    constraint uq_users_username
        unique (username),

    constraint uq_users_email
        unique (email),

    constraint chk_users_role
        check (role IN ('BUYER', 'SELLER', 'ADMIN'))
);