spring.application.name=product-service

server.port=${SERVER_PORT:8082}

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:1012/marketplace_products}
spring.datasource.username=${DB_USER:marketplace}
spring.datasource.password=${DB_PASSWORD:marketplace}
spring.grpc.client.channel.user-service.target=static://${USER_GRPC_TARGET:localhost:9091}
spring.grpc.client.channel.user-service.ssl.enabled=false